all:
	gcc -o p1_fifo p1_fifo.c
	gcc -o p2_fifo p2_fifo.c
	gcc -o p1_socket p1_socket.c
	gcc -o p2_socket p2_socket.c
	gcc -o p1_shared_memory p1_shared_memory.c
	gcc -o p2_shared_memory p2_shared_memory.c
clean:
	rm -rf p1_fifo p2_fifo p1_socket p2_socket p1_shared_memory p2_shared_memory
