all:
	gcc -o part_a dinning_philospher_strict_ordering.c
	gcc -o part_b dinning_philospher_semaphore.c 
	gcc -o part_c dinning_philospher_sauce_strictorder.c
	gcc -o part_d dinning_philospher_sauce.c

clean:
	rm -f part_a part_b part_c part_d
